# Uncomment this line to define a global platform for your project
platform :osx, '10.11'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Tests-Pods-macOS' do
  pod 'SignalProtocolC', :podspec => '../SignalProtocolC.podspec'
end